artifact_uri: file:///home/mle-user/mle_projects/mlflow/mlflow_experiments_store/0/69a8161570144ddb8455b2d3888f3780/artifacts
end_time: 1731673534227
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 69a8161570144ddb8455b2d3888f3780
run_name: Default
run_uuid: 69a8161570144ddb8455b2d3888f3780
source_name: ''
source_type: 4
source_version: ''
start_time: 1731673534212
status: 3
tags: []
user_id: mle-user
