artifact_location: file:///home/mle-user/mle_projects/mlflow/mlflow_experiments_store/0
creation_time: 1731673343508
experiment_id: '0'
last_update_time: 1731673343508
lifecycle_stage: active
name: Default
